import { useQueryClient } from "@tanstack/react-query";
import { Column } from "primereact/column";
import { DataTable } from "primereact/datatable";
import { Paginator } from "primereact/paginator";
import { useState } from "react";

interface Country {
  name: string;
  code: string;
}

interface Representative {
  name: string;
  code: string;
}

interface Customer {
  id: number;
  name: string;
  country: Country;
  company: string;
  date: string;
  status: string;
  verified: boolean;
  activity: number;
  representative: Representative;
  balance: number;
}

const User = () => {
  const [customers, setCustomers] = useState<Customer[]>([
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
    {
      id: 1,
      name: "John Doe",
      country: { name: "United States", code: "US" },
      company: "ABC Inc.",
      date: "2024-05-06",
      status: "Active",
      verified: true,
      activity: 10,
      representative: { name: "Alice Smith", code: "AS" },
      balance: 1000,
    },
    {
      id: 2,
      name: "Jane Smith",
      country: { name: "Canada", code: "CA" },
      company: "XYZ Ltd.",
      date: "2024-05-06",
      status: "Inactive",
      verified: false,
      activity: 5,
      representative: { name: "Bob Johnson", code: "BJ" },
      balance: 500,
    },
  ]);

  return (
    <>
      <DataTable
        value={customers}
        // paginator
        rows={5}
        rowsPerPageOptions={[5, 10, 25, 50]}
      >
        <Column field="name" header="Name" style={{ width: "25%" }}></Column>
        <Column
          field="country.name"
          header="Country"
          style={{ width: "25%" }}
        ></Column>
        <Column
          field="company"
          header="Company"
          style={{ width: "25%" }}
        ></Column>
        <Column
          field="representative.name"
          header="Representative"
          style={{ width: "25%" }}
        ></Column>
      </DataTable>
      <Paginator
        first={0}
        rows={5}
        totalRecords={120}
        rowsPerPageOptions={[10, 20, 30]}
        // onPageChange={onPageChange}
      />
    </>
  );
};

export default User;
